[project]
name = "video2article"
version = "1.0.0"
description = "Multi-lingual Video Transcription Sample using Amazon Bedrock"
readme = "README.md"
requires-python = ">=3.12"
license = {text = "MIT"}